Move state logic to state.rs
opencloudtool/opencloudtool pull request #23
Opened 2024-12-20 06:26 UTC by andagaev

2024-12-24 08:22 UTC, minev-dev requested changes

2024-12-24 08:22 UTC, minev-dev commented on crates/oct-cloud/src/state.rs
> +    }
You don't need this logic, it's already implemented in `aws::Ec2Instance::new`.

The same idea should be followed in the `InstanceProfileState` and `InstanceRoleState`

2024-12-24 08:22 UTC, minev-dev commented on crates/oct-cloud/src/aws.rs
> +                            .public_dns_name(String::new())
Should they be `None`?

2024-12-24 08:22 UTC, minev-dev commented on crates/oct-cloud/src/aws.rs
> +    pub client: IAM,
`client` shouldn't be public, it's an implementation detail

2024-12-24 08:22 UTC, minev-dev commented on crates/oct-cloud/src/aws.rs
> +    pub client: IAM,
`client` shouldn't be public, it's an implementation detail

2024-12-24 08:22 UTC, minev-dev commented on crates/oct-cloud/src/aws.rs
> +            self.public_dns.clone().unwrap(),
Don't use `unwrap` in the production code. It'll cause panic

2024-12-24 08:22 UTC, minev-dev commented on crates/oct-cloud/src/aws.rs
> +        }
What do you think about moving this logic to a private method?

2024-12-24 08:22 UTC, minev-dev commented on crates/oct-cloud/src/aws.rs
> +                            }
Is it possible to have only one of them not None? I suppose if one of them is available, another one should also be available

2024-12-24 08:22 UTC, minev-dev commented on crates/oct-cloud/src/aws.rs
> +        tokio::time::sleep(std::time::Duration::from_secs(30)).await;
Do we really need this sleep if we already have enough number of attempts getting the metadata?

2024-12-24 08:22 UTC, minev-dev commented on crates/oct-cloud/src/aws.rs
> +                        if let Some(instance) = reservation.instances().get(0) {
Can you avoid using so deep nesting?

2024-12-24 08:22 UTC, minev-dev commented on crates/oct-cloud/src/aws.rs
> +    pub client: Ec2,
`client` shouldn't be public, it's an implementation detail

2024-12-24 08:22 UTC, minev-dev commented on crates/oct-cloud/src/aws.rs
> +pub use MockIAMImpl as IAM;
These clients shouldn't be public, it's an implementation detail

2024-12-24 08:22 UTC, minev-dev commented on crates/oct-cloud/src/aws.rs
> +    pub fn new(inner: aws_sdk_iam::Client) -> Self {
It shouldn't be public, it's for internal use only

2024-12-24 08:22 UTC, minev-dev commented on crates/oct-cloud/src/aws.rs
>  }
This code shouldn't be public, it's for internal use only

2024-12-24 08:22 UTC, minev-dev commented on crates/oct-cloud/src/aws.rs
> +    pub fn new(inner: aws_sdk_ec2::Client) -> Self {
This code shouldn't be public, it's for internal use only

2024-12-28 20:50 UTC, minev-dev approved these changes

2024-12-29 07:08 UTC, olegasics approved these changes

2024-12-29 07:15 UTC, merged